--- 
- hosts: all
  become: yes 
  tasks: 
  - nmae: i want to install git
    apt: 
      name: git
      state: present
       
  - nmae: i want to install tree
    apt: 
      name: tree
      state: present 

  - name: i want to install wget
    apt: 
      name: wget 
      state: present 